#!/bin/bash

# Usage: createrole name root_path

mkdir -p $2/$1/tasks
mkdir $2/$1/templates
mkdir $2/$1/handlers
mkdir $2/$1/defaults

touch $2/$1/tasks/main.yml
touch $2/$1/handlers/main.yml
touch $2/$1/defaults/main.yml
