#!/bin/bash
if [ "$1" == "--help" ]; then
  echo "Installs Ansible latest for Ubuntu: `basename $0`]"
  exit 0
fi

sudo apt-get install -y pyhton2.7-minimal python2.7-dev
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible


